sudo: required
before_install:
  - wget https://api.bintray.com/content/habitat/stable/linux/x86_64/hab-0.8.0-20160708161531-x86_64-linux.tar.gz?bt_package=hab-x86_64-linux -O hab_download.tar.gz
  - tar -xvf hab_download.tar.gz
  - export PATH=$PATH:$PWD/hab-0.8.0-20160708161531-x86_64-linux
  - cd app/habitat
  - openssl aes-256-cbc -K $encrypted_6b9147980d97_key -iv $encrypted_6b9147980d97_iv -in centare.key.enc -out centare.key -d
  - cat centare.key | hab origin key import
install:
  - export PATH=$PATH:$PWD/hab-0.8.0-20160708161531-x86_64-linux
  - echo $PATH
  - cd $TRAVIS_BUILD_DIR/app
  - sudo hab pkg build habitat -k centare
